### ISSUE TITLE
[Qiita記事]固有値、固有ベクトルの便利さを二次形式と微分方程式から体感する

### ISSUE THREAD

**Issue by takanoshuhei** [furukawa-laboratory/workout_report_2019#100]
## 執筆するQiita記事の概要
固有値、固有ベクトルの概要を説明したうえで、どのような場面で便利なのかを二次形式と微分方程式の例から体感することで固有値、固有ベクトルに対する理解を深める。
「ゼロから学ぶ線形代数」という本に詳しく乗っているのでそれを理解し、参考にしながら執筆する。

## 取り組む期間
~7/1までにプルリクを出す予定です
## 獲得を目指すスキル
- 固有値固有ベクトルって結局何なの？どう便利なの？という疑問を払拭する
## Action list
- [x] ゼロから学ぶ線形代数6章を理解する
- [ ] 機械学習のエッセンスから、機械学習における固有値、固有ベクトルの立ち位置を理解する（予定）
- [ ] ミニレポート提出

**Comment by ae14watanabe** [comment]
次からは`final report` のラベル付けといてもらえると！

**Comment by takanoshuhei** [comment]
申し訳ないです。忘れてました！
