### ISSUE TITLE
［ビギナー］データの前処理の概要を捉える

### ISSUE THREAD

**Issue by Kusumoto-Keisuke** [furukawa-laboratory/workout_report_2019#48]
## 取り組むトレーニングの概要
資料：Data Preprocessing, Analysis & Visualization – Python Machine Learning を写経して”データの前処理”について概観をつかむ．さらに実際に PCA によるデータセットの可視化を実装してみる．

## 取り組む期間
～ 2019 年 4 月 26 日  

## 獲得を目指すスキル
データの前処理とは何かを理解する．

## Action list
- [x] 資料を jupyter notebook に写経し，動作確認をする．
- [ ] 上記にPCAを用いてデータセットを可視化する処理を追加実装する．
- [ ] 前処理の外観をつかむ．

**Comment by hajime9652** [comment]
できた？
期間の設定の仕方に無理があるかと(作業量的にも、学習効率としても)

**Comment by Kusumoto-Keisuke** [comment]
写経すら終わりませんでした．4/26 まで期間を延ばします．ご指摘ありがとうございます．

**Comment by hajime9652** [comment]
写経と動作確認はできたようなのでクローズしておきます
